[package]
name = "FluxAggregator"
version = "0.1.0"
authors = ["kwsantiago <kwsantiago@usf.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.0.1"
num-traits = "0.2"
